DROP DATABASE TaskJiraTest;
CREATE DATABASE TaskJiraTest;

DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS DEVELOPER;

CREATE TABLE TASK(

TASKID 			VARCHAR(20) 	NOT NULL,
DESCRIPTION		VARCHAR(256)	NOT NULL,
DURATION		INTEGER			NOT NULL,
DEVELOPER		VARCHAR(100)    NOT NULL,


PRIMARY KEY (TASKID)
);

CREATE TABLE DEVELOPER(
TOKEN 			VARCHAR(256) 	NOT NULL,
DEV_NAME 		VARCHAR(100) 	NOT NULL,
ISADMIN 		BIT 			NOT NULL,

PRIMARY KEY(TOKEN)
);

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_HEEFT_EEN_DEVELOPER FOREIGN KEY (DEVELOPER)
      REFERENCES DEVELOPER (TOKEN) ON DELETE CASCADE ON UPDATE CASCADE;